//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class raaTcpSocket
{
	protected virtual object QMutex m_Mutex
	{
		get;
		set;
	}

	public raaTcpSocket(object QObject *pParent = 0)
	{
	}

	public virtual void virtual ~raaTcpSocket()
	{
		throw new System.NotImplementedException();
	}

	protected virtual void customEvent(object QEvent *pEvent)
	{
		throw new System.NotImplementedException();
	}

}

